name: echo-mate-rv1106

services:
  sdk:
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: echo-mate-rv1106-dev:ubuntu22.04-amd64
    stdin_open: true
    tty: true
    working_dir: /workspace/Echo-Mate
    environment:
      - http_proxy=http://host.docker.internal:7897
      - https_proxy=http://host.docker.internal:7897
    volumes:
      - echo-mate-sdk:/workspace
      - .:/host-project:ro

volumes:
  echo-mate-sdk:
    name: echo-mate-sdk
