name: echo-mate-rv1106

services:
  sdk:
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: echo-mate-rv1106-dev:ubuntu22.04-amd64
    stdin_open: true
    tty: true
    working_dir: /workspace/Echo-Mate
    environment:
      - PROXY_HOST=${PROXY_HOST:-host.docker.internal}
      - PROXY_PORT=${PROXY_PORT:-7897}
    volumes:
      - echo-mate-sdk:/workspace
      - .:/host-project:ro

volumes:
  echo-mate-sdk:
    name: echo-mate-sdk
